### ISSUE TITLE
[BUG]  學期成績  獎懲紀錄 內容無法顯示

### ISSUE THREAD

**Issue by an-777** [tobiichi3227/TNFSH-Scoreboard#13]
**Describe the bug**

**To Reproduce**
1. Go to '學期成績'
2. Click on '112上'
3. See error

**Expected behavior**

**Screenshots**
<img width="875" alt="image" src="https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/131597737/7aaef431-088c-4c55-a1ba-bb982060e4df">
<img width="884" alt="image" src="https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/131597737/dfc147d6-efde-49c6-ae92-c083144f0aa1">

**Desktop or Mobile Device (please complete the following information):**

**Additional context**

**Comment by tobiichi3227** [comment]
抱歉，有些條件沒判斷到
