### ISSUE TITLE
「選擇學期」清單希望能排序

### ISSUE THREAD

**Issue by LenLai3652** [tobiichi3227/TNFSH-Scoreboard#14]
如圖
![Screenshot_2024-01-24-13-58-15-84_a23b203fd3aafc6dcb84e438dda678b6](https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/106729286/51679dad-fdae-4365-8000-a51553af59cd)

**Comment by tobiichi3227** [comment]
您不說我還不知道
太尷尬了
