### ISSUE TITLE
[BUG] 180 Days Change Password

### ISSUE THREAD

**Issue by EF-Lin** [tobiichi3227/TNFSH-Scoreboard#16]
假如觸發校務系統的180天後要改密碼的程序，網站會跳出警告訊息並重新載入登入介面，但實際上已登入成功，而且可查看資料，不影響使用。
或許能將這點加以運用，繞過校務系統限制，~~順便嘲諷寫校務系統網站的工程師~~。

**Comment by tobiichi3227** [comment]
我想工程師根本沒想到會有人這樣做吧🤣
