### ISSUE TITLE
充分利用更改密碼的Bug

### ISSUE THREAD

**Issue by EF-Lin** [tobiichi3227/TNFSH-Scoreboard#17]
可以利用180天更改密碼的功能讓使用者能在一天內更改~~一百萬次~~密碼。

**Comment by tobiichi3227** [comment]
這個已經在[afa802d](https://github.com/tobiichi3227/TNFSHScoreboard/commit/afa802d6f3dfc45ef04fbf43dcf9f5ebd55bc522)實現了
