### ISSUE TITLE
[BUG] 如果段考分數為空 選單會不見

### ISSUE THREAD

**Issue by an-777** [tobiichi3227/TNFSH-Scoreboard#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/131597737/9bb958e6-017a-4636-885a-7f114d0be560)
![image](https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/131597737/315d93da-43be-46ab-97bc-6cbf5f130766)

**Desktop or Mobile Device (please complete the following information):**
iOS safari 

**Additional context**

**Comment by tobiichi3227** [comment]
似乎是因為目前流量較大
校務系統沒有回應

**Comment by EF-Lin** [comment]
校務系統的伺服器：![image](https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/79702669/4983ccbb-32b9-4463-bef4-efaef078d74b)

**Comment by tobiichi3227** [comment]
今天真的嗨
