### ISSUE TITLE
Suggestion for adding issues template

### ISSUE THREAD

**Issue by Skywind5487** [tobiichi3227/TNFSH-Scoreboard#7]
I think this repo deserves to have an issues template.
Here's some suggestion:

https://github.com/Polymer/polymer/blob/master/.github/ISSUE_TEMPLATE.md
https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/blob/master/issue_template.md

origin:https://github.com/devspace/awesome-github-templates

**Comment by tobiichi3227** [comment]
ok, i will think about what kind of issues template we should add.

**Comment by tobiichi3227** [comment]
I add some template by changing github default template

**Comment by Skywind5487** [comment]
It's awesome! Thank you for your issue template!
