### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Skywind5487** [tobiichi3227/TNFSH-Scoreboard#8]
**Describe the bug**

When I use edge as my browser and open the Microsoft translate on my iPhone 14 and iPad,I can't choose the exam on drop-down list.

**To Reproduce**
1. Go to 'https://toj.tfcis.org/board/exam/'
2. login.
3. The drop-down list is not able to click.See error.

**Expected behavior**

There are some exam can be choose on the drop-down list.

**Screenshots**

![image](https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/101578572/fa199cfb-827c-4cc0-8059-1925b21d7c54)
from iPhone

![image](https://github.com/tobiichi3227/TNFSH-Scoreboard/assets/101578572/36a2f1e5-8295-4188-adc7-336e65da3364)

from iPad
**Desktop or Mobile Device (please complete the following information):**
 - Browser : both are edge
 - Device : iPad Air 5 and iPhone 14
**Additional context**

**Comment by tobiichi3227** [comment]
I cannot reproduce this bug in my android phone with edge.
